[project]
name = "dbgear-doc"
version = "0.3.0"
description = "Documentation generator plugin for DBGear"
authors = [
    {name = "tamuto", email = "mutomob@gmail.com"}
]
readme = "README.md"
license = "MIT"
requires-python = ">=3.12,<4.0"
dependencies = [
    "dbgear>=0.40.0",
    "in4viz>=0.3.0",
]

[project.entry-points."dbgear.commands"]
dbgear-doc = "dbgear_doc.command"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [
    { include = "dbgear_doc" }
]

[tool.poetry.group.dev.dependencies]
taskipy = "^1.14.1"
flake8 = "^7.3.0"
dbgear = {path = "../dbgear", develop = true}

[tool.taskipy.tasks]
test = "poetry run python -m unittest discover tests/ -v"
lint = "poetry run flake8 dbgear_doc/ tests/"
