[project]
name = "dbgear-doc"
version = "0.2.0"
description = "Documentation generator plugin for DBGear"
authors = [
    {name = "tamuto", email = "mutomob@gmail.com"}
]
readme = "README.md"
license = "MIT"
requires-python = ">=3.12,<4.0"
dependencies = [
    "dbgear>=0.39.0",
    "in4viz>=0.3.0",
]

[project.entry-points."dbgear.plugins"]
doc = "dbgear_doc:generate_docs"
svg = "dbgear_doc.er_diagram:generate_svg"
drawio = "dbgear_doc.er_diagram:generate_drawio"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [
    { include = "dbgear_doc" }
]

[tool.poetry.group.dev.dependencies]
taskipy = "^1.14.1"
flake8 = "^7.3.0"

[tool.taskipy.tasks]
test = "poetry run python -m unittest discover tests/ -v"
lint = "poetry run flake8 dbgear_doc/ tests/"
